enableRobotsTXT = true
canonifyURLs = true
baseurl = "https://eludom.github.io/"
publishDir = "docs"
languageCode = "en-us"
title = "Curious Musings"
themesDir = "themes"
theme = "hyde"
disqusShortname = "curiousmusings"
footnoteReturnLinkContents = "[^ back]"

name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "Just a theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.21

[author]
    name = "George Jones"
    homepage = "eludom.github.io"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"

[params]
    description = "A Blog by George Jones: Musings on life, computers, security, etc.."
    themeColor = "theme-base-0a"

[taxonomies]
    tags="tags"
